name: Vercel Next.js Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v3

      - name: Node.js のセットアップ
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Vercel CLI のインストールと更新
        run: |
          npm install -g vercel@latest
          vercel --version

      - name: デバッグ情報の表示
        run: |
          echo "Vercel Token is set: ${{ secrets.VERCEL_TOKEN != '' }}"
          echo "Vercel Project ID: $VERCEL_PROJECT_ID"
          echo "Vercel Org ID: $VERCEL_ORG_ID"

      - name: Vercel へのデプロイ
        run: |
          echo "Vercel デプロイを開始します..."
          vercel pull --yes --environment=production --token ${{ secrets.VERCEL_TOKEN }}
          vercel build --prod --token ${{ secrets.VERCEL_TOKEN }}
          DEPLOYMENT_URL=$(vercel deploy --prebuilt --prod --token ${{ secrets.VERCEL_TOKEN }})
          echo "DEPLOYMENT_URL=$DEPLOYMENT_URL" >> $GITHUB_ENV
          echo "デプロイされた URL: $DEPLOYMENT_URL"

      - name: デプロイメントチェック
        if: env.DEPLOYMENT_URL
        run: |
          echo "チェックする一時URL: ${{ env.DEPLOYMENT_URL }}"
          echo "チェックする本番URL: https://x-clone-test.vercel.app"
          timeout 5m bash -c '
            until curl -s -o /dev/null -w "%{http_code}" ${{ env.DEPLOYMENT_URL }} | grep -q "200\|204" && \
                  curl -s -o /dev/null -w "%{http_code}" https://x-clone-test.vercel.app | grep -q "200\|204"; do
              echo "Waiting for deployment..."
              sleep 10
            done
          '
          if [ $? -eq 0 ]; then
            echo "デプロイメントが成功しました。"
          else
            echo "デプロイメントが失敗しました。タイムアウトまたはエラーが発生しました。"
            exit 1
          fi

      - name: デプロイメント状態の確認
        if: failure()
        run: |
          echo "デプロイメント状態を確認しています..."
          vercel inspect ${{ env.DEPLOYMENT_URL }} --token ${{ secrets.VERCEL_TOKEN }}

      - name: Vercel デプロイログの確認
        if: always() && env.DEPLOYMENT_URL
        run: |
          echo "デプロイメントログを確認しています..."
          timeout 30s vercel logs ${{ env.DEPLOYMENT_URL }} --token ${{ secrets.VERCEL_TOKEN }} --limit 50

      - name: プロジェクト情報の確認
        if: failure()
        run: |
          echo "プロジェクト情報を確認しています..."
          vercel project ls --token ${{ secrets.VERCEL_TOKEN }}