name: Functions と Vercel のデプロイ

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Node.js のセットアップ
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: 環境変数の設定
        run: |
          echo 'FIREBASE_CONFIG<<EOF' >> $GITHUB_ENV
          echo '${{ secrets.FIREBASE_CONFIG }}' >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
          echo "MY_FIREBASE_PROJECT_ID=${{ secrets.MY_FIREBASE_PROJECT_ID }}" >> $GITHUB_ENV
          echo "MY_FIREBASE_CLIENT_EMAIL=${{ secrets.MY_FIREBASE_CLIENT_EMAIL }}" >> $GITHUB_ENV
          echo 'MY_FIREBASE_PRIVATE_KEY<<EOF' >> $GITHUB_ENV
          echo "${{ secrets.MY_FIREBASE_PRIVATE_KEY }}" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
          echo "FIREBASE_TOKEN=${{ secrets.FIREBASE_TOKEN }}" >> $GITHUB_ENV
          echo "VERCEL_ORG_ID=${{ secrets.VERCEL_ORG_ID }}" >> $GITHUB_ENV
          echo "VERCEL_PROJECT_ID=${{ secrets.VERCEL_PROJECT_ID }}" >> $GITHUB_ENV
          echo "VERCEL_TOKEN=${{ secrets.VERCEL_TOKEN }}" >> $GITHUB_ENV
          
      - name: Firebase 認証情報の設定
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}" | base64 -d > /tmp/firebase-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=/tmp/firebase-key.json" >> $GITHUB_ENV

      - name: Vercel 認証情報の設定
        run: |
          echo "VERCEL_TOKEN=${{ secrets.VERCEL_TOKEN }}" >> $GITHUB_ENV
          echo "VERCEL_ORG_ID=${{ secrets.VERCEL_ORG_ID }}" >> $GITHUB_ENV
          echo "VERCEL_PROJECT_ID=${{ secrets.VERCEL_PROJECT_ID }}" >> $GITHUB_ENV


      - name: サービスアカウントキーのセットアップ
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}" > /tmp/gcp-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcp-key.json" >> $GITHUB_ENV

      - name: 環境変数の確認
        run: |
          echo "FIREBASE_CONFIG は設定されています: ${{ env.FIREBASE_CONFIG != '' }}"
          echo "MY_FIREBASE_PROJECT_ID: ${{ env.MY_FIREBASE_PROJECT_ID }}"
          echo "MY_FIREBASE_CLIENT_EMAIL は設定されています: ${{ env.MY_FIREBASE_CLIENT_EMAIL != '' }}"
          echo "MY_FIREBASE_PRIVATE_KEY は設定されています: ${{ env.MY_FIREBASE_PRIVATE_KEY != '' }}"
          echo "GOOGLE_APPLICATION_CREDENTIALS: $GOOGLE_APPLICATION_CREDENTIALS"
          echo "FIREBASE_TOKEN は設定されています: ${{ env.FIREBASE_TOKEN != '' }}"
          echo "VERCEL_ORG_ID は設定されています: ${{ env.VERCEL_ORG_ID != '' }}"
          echo "VERCEL_PROJECT_ID は設定されています: ${{ env.VERCEL_PROJECT_ID != '' }}"
          echo "VERCEL_TOKEN は設定されています: ${{ env.VERCEL_TOKEN != '' }}"

      - name: 環境変数の詳細確認
        run: |
          echo "環境変数の詳細:"
          for var in FIREBASE_CONFIG MY_FIREBASE_PROJECT_ID MY_FIREBASE_CLIENT_EMAIL MY_FIREBASE_PRIVATE_KEY GOOGLE_APPLICATION_CREDENTIALS FIREBASE_TOKEN VERCEL_ORG_ID VERCEL_PROJECT_ID VERCEL_TOKEN
          do
            value="${!var}"
            echo "$var:"
            echo "  長さ: ${#value}"
            echo "  最初の3文字: ${value:0:3}"
            echo "  最後の3文字: ${value: -3}"
            echo "---"
          done


      - name: GOOGLE_APPLICATION_CREDENTIALS の確認
        run: |
          if [ -f "$GOOGLE_APPLICATION_CREDENTIALS" ]; then
            echo "GOOGLE_APPLICATION_CREDENTIALS ファイルが存在します"
            echo "ファイルの内容（最初の3行）:"
            head -n 3 "$GOOGLE_APPLICATION_CREDENTIALS"
          else
            echo "GOOGLE_APPLICATION_CREDENTIALS ファイルが見つかりません"
          fi

      - name: FIREBASE_TOKEN のデバッグ
        run: |
          if [ -n "$FIREBASE_TOKEN" ]; then
            echo "FIREBASE_TOKEN is set"
            echo "FIREBASE_TOKEN length: ${#FIREBASE_TOKEN}"
          else
            echo "FIREBASE_TOKEN is not set"
          fi
          
      - name: Vercel 環境変数のデバッグ
        run: |
          for var in VERCEL_ORG_ID VERCEL_PROJECT_ID VERCEL_TOKEN
          do
            if [ -n "${!var}" ]; then
              echo "$var is set"
              echo "$var length: ${#var}"
            else
              echo "$var is not set"
            fi
          done

      - name: 依存関係のキャッシュ
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-

      - name: ルートの依存関係をインストール
        run: npm ci

      - name: Firebase CLI のインストールと更新
        run: |
          npm install -g firebase-tools
          firebase --version

      - name: サービスアカウントキーのセットアップ
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}" | base64 -d > /tmp/gcp-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcp-key.json" >> $GITHUB_ENV


      - name: サービスアカウントキーの確認
        run: |
          echo "サービスアカウントキーの内容（秘密鍵を除く）:"
          jq 'del(.private_key)' $GOOGLE_APPLICATION_CREDENTIALS

      - name: Next.js アプリのビルド
        run: npm run build:next
        env:
          CI: true

      - name: Functions のインストールとビルド
        run: |
          cd functions
          npm ci
          npm run build
          cp -r lib/* .

      - name: vercel.json の確認
        run: |
          if [ -f vercel.json ]; then
            echo "vercel.json が存在します。内容:"
            cat vercel.json
          else
            echo "vercel.json が存在しません。基本的な vercel.json ファイルを作成します。"
            echo '{
              "version": 2,
              "builds": [
                {
                  "src": "package.json",
                  "use": "@vercel/next"
                }
              ]
            }' > vercel.json
          fi

      - name: Firebase プロジェクトの設定
        run: firebase use ${{ secrets.MY_FIREBASE_PROJECT_ID }}
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/gcp-key.json

      - name: Firebase 設定のデバッグ
        run: |
          echo "Firebase プロジェクトリスト:"
          firebase projects:list
          echo "現在のプロジェクト設定:"
          firebase use
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/gcp-key.json

      - name: Firebase Functions のデプロイ
        run: |
          
          firebase deploy --only functions --project ${{ secrets.FIREBASE_PROJECT_ID }} --token "${{ secrets.FIREBASE_TOKEN }}"
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/gcp-key.json
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          MY_FIREBASE_PROJECT_ID: ${{ secrets.MY_FIREBASE_PROJECT_ID }}
          MY_FIREBASE_CLIENT_EMAIL: ${{ secrets.MY_FIREBASE_CLIENT_EMAIL }}
          MY_FIREBASE_PRIVATE_KEY: ${{ secrets.MY_FIREBASE_PRIVATE_KEY }}

      - name: Functions URL の取得
        run: |
          FUNCTIONS_URL=$(firebase functions:shell | grep "deleteUser" | awk '{print $2}')
          echo "Functions URL: $FUNCTIONS_URL"
          echo "FUNCTIONS_URL=$FUNCTIONS_URL" >> $GITHUB_ENV
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/gcp-key.json

      - name: 更新前の vercel.json のデバッグ
        run: cat vercel.json

      - name: vercel.json を Functions URL で更新
        run: |
          if [ -n "$FUNCTIONS_URL" ]; then
            cp vercel.json vercel.json.bak
            jq --arg url "$FUNCTIONS_URL" '.rewrites[0].destination = $url' vercel.json > vercel.json.tmp && mv vercel.json.tmp vercel.json
            echo "更新された vercel.json の内容:"
            cat vercel.json
          else
            echo "警告: Functions URL で vercel.json の更新に失敗しました"
          fi

      - name: vercel.json の検証
        run: |
          if jq empty vercel.json 2>/dev/null; then
            echo "vercel.json は有効な JSON です。"
          else
            echo "vercel.json は有効な JSON ではありません。内容:"
            cat vercel.json
            exit 1
          fi

      - name: Vercel へのデプロイ
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          npx vercel pull --yes --environment=production --token $VERCEL_TOKEN
          npx vercel build --prod --token $VERCEL_TOKEN
          DEPLOYMENT_URL=$(npx vercel deploy --prebuilt --prod --token $VERCEL_TOKEN)
          echo "DEPLOYMENT_URL=$DEPLOYMENT_URL" >> $GITHUB_ENV
          echo "デプロイメント URL: $DEPLOYMENT_URL"

      - name: デプロイメントチェック
        run: |
          if [ -z "$DEPLOYMENT_URL" ]; then
            echo "エラー: デプロイメント URL が設定されていません"
            exit 1
          fi
          echo "チェックする URL: $DEPLOYMENT_URL"
          HTTP_RESPONSE=$(curl -sS -o /dev/null -w "%{http_code}" $DEPLOYMENT_URL)
          echo "HTTP ステータスコード: $HTTP_RESPONSE"
          if [ $HTTP_RESPONSE = "200" ] || [ $HTTP_RESPONSE = "404" ]; then
            echo "デプロイメントが成功しました。ステータスコード: $HTTP_RESPONSE"
          else
            echo "デプロイメントが失敗しました。ステータスコード: $HTTP_RESPONSE"
            curl -sS $DEPLOYMENT_URL
            exit 1
          fi